export const connectKitStyle = {
  "--ck-font-family": "Mukta",
  "--ck-body-color": "#000000",
  "--ck-border-radius": "16px",
  "--ck-overlay-background": "rgba(167, 130, 255, 0.7225199346492454)",
  "--ck-overlay-backdrop-filter": "blur(0px)",
  "--ck-primary-button-color": "#ffffff",
  "--ck-primary-button-background": "#7d61bf",
  "--ck-primary-button-box-shadow": "0px 0px 0px 1px #7d61bf",
  "--ck-primary-button-border-radius": "16px",
  "--ck-primary-button-font-weight": "500",
  "--ck-primary-button-hover-color": "#ffffff",
  "--ck-primary-button-hover-background": "#563a98",
  "--ck-primary-button-hover-box-shadow": "0px 0px 0px 0px #563a98",
  "--ck-primary-button-active-background": "#7d61bf",
  "--ck-primary-button-active-box-shadow": "0px 3px 0px 0px #7d61bf",
  "--ck-secondary-button-color": "#ffffff",
  "--ck-secondary-button-background": "#7d61bf",
  "--ck-secondary-button-box-shadow": "0px 1px 0px 1px #7d61bf",
  "--ck-secondary-button-border-radius": "16px",
  "--ck-secondary-button-font-weight": "800",
  "--ck-secondary-button-hover-color": "#ffffff",
  "--ck-secondary-button-hover-background": "#563a98",
  "--ck-secondary-button-hover-box-shadow": "0px 3px 0px 0px #563a98",
  "--ck-secondary-button-active-background": "#7d61bf",
  "--ck-secondary-button-active-box-shadow": "0px 2px 0px 1px #7d61bf",
  "--ck-tertiary-button-color": "#ffffff",
  "--ck-tertiary-button-background": "#7d61bf",
  "--ck-tertiary-button-box-shadow": "0px 3px 0px 1px #7d61bf",
  "--ck-tertiary-button-border-radius": "16px",
  "--ck-tertiary-button-font-weight": "800",
  "--ck-tertiary-button-hover-color": "#ffffff",
  "--ck-tertiary-button-hover-background": "#563a98",
  "--ck-tertiary-button-hover-box-shadow": "0px 2px 0px 1px #563a98",
  "--ck-modal-box-shadow": "0px 2px 0px 1px #ede6ff",
  "--ck-body-background": "#ede6ff",
  "--ck-body-background-secondary": "#ede6ff",
  "--ck-body-background-tertiary": "#ede6ff",
  "--ck-body-color-muted": "#000000",
  "--ck-body-color-muted-hover": "#000000",
  "--ck-body-color-danger": "#000000",
  "--ck-body-color-valid": "#000000",
  "--ck-modal-heading-font-weight": "600",
  "--ck-focus-color": "#ffffff",
  "--ck-body-action-color": "#000000",
  "--ck-body-divider": "#ede6ff",
  "--ck-qr-dot-color": "#ffffff",
  "--ck-qr-background": "#a782ff",
  "--ck-qr-border-color": "#ffffff",
  "--ck-qr-border-radius": "16px",
  "--ck-tooltip-color": "#ffffff",
  "--ck-tooltip-background": "#a782ff",
  "--ck-tooltip-background-secondary": "#a782ff",
  "--ck-tooltip-shadow": "0px 2px 0px 0px #a782ff",
  "--ck-spinner-color": "#ffffff",
  "--ck-recent-badge-color": "#ffffff",
  "--ck-recent-badge-background": "#a782ff",
  "--ck-recent-badge-border-radius": "16px",
  "--ck-body-disclaimer-color": "#000000",
  "--ck-body-disclaimer-link-color": "#000000",
  "--ck-body-disclaimer-link-hover-color": "#000000",
  "--ck-body-disclaimer-background": "#ede6ff",
  "--ck-connectbutton-font-size": "18px",
  "--ck-connectbutton-border-radius": "16px",
  "--ck-connectbutton-color": "#ffffff",
  "--ck-connectbutton-background": "#7d61bf",
  "--ck-connectbutton-box-shadow": "0px 1px 0px 0px #7d61bf",
  "--ck-connectbutton-hover-color": "#ffffff",
  "--ck-connectbutton-hover-background": "#563a98",
  "--ck-connectbutton-hover-box-shadow": "0px 3px 0px 0px #563a98",
  "--ck-connectbutton-active-color": "#ffffff",
  "--ck-connectbutton-active-background": "#7d61bf",
  "--ck-connectbutton-active-box-shadow": "0px 1px 0px 1px #7d61bf"
};